; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanorp2040connect]
platform = raspberrypi
board = nanorp2040connect
framework = arduino
lib_deps = 
	askuric/Simple FOC@^2.4.0
	simplefoc/SimpleFOCDrivers@^1.0.9
	arduino-libraries/Arduino_LSM6DS3@^1.0.3
	hideakitai/ArduinoEigen@^0.3.2
